export const APPRoutes = {
	start: "/",
	home: "/home",
	news: '/news',
	editNews: '/edit-news/',
	addNews: '/add-news',
	forum: "/forum",
	game: '/game/',
	games: '/games',
	tables: '/tables',
	stats: '/stats',
	contacts: '/contacts',
	trophies: '/trophies',
	statistics: '/statistics',
	playerStats: '/player',
	privacy: '/privacy',

	adminNews: "/admin-news",
	adminSettings: "/admin-settings",
	adminGames: "/admin-games",
	adminPlayers: "/admin-players",
	adminForum: "/admin-forum",
	adminSocial: "/admin-social",
	adminLevels: "/admin-levels",
	adminShop: "/admin-shop",
	adminForumReports: "/forum-reports",
	adminTrophy: "/admin-trophy",
	addTrophy: '/add-trophy',
	editTrophy: '/edit-trophy/',

	updateGame: '/update-game/',
	addShopElement: "/addShopElement",
	editShopElement: "/editShopElement",
};
